In [3]:
import importlib
import ewxndfd.ndfd_forecast_api

from ewxndfd import ndfd_forecast_api as ndfd
print(ndfd.DEFAULT_USER_AGENT)

(enviroweather.msu.edu, ewx@enviroweather.msu.edu)

In [4]:
lat, lon = ndfd.LANSING_LAT_LON
 
daily_forecast_df = ndfd.daily_forecast_summary(lat=lat, lon = lon, 
                                                hourly_weather=None, 
                                                units = 'US')

In [5]:
daily_forecast_df

,forecast_date,Daily Minimum Temperature (Fahrenheit),Daily Maximum Temperature (Fahrenheit),Maximum Relative Humidity (percent),Minimum Relative Humidity (percent),Total Liquid Precipitation Amount (inches),latitude,longitude
0,2026-06-19,53.0,73,67,42,0.00,42.78,-84.6
1,2026-06-20,53.0,75,90,49,0.03,42.78,-84.6
2,2026-06-21,55.0,75,93,53,0.25,42.78,-84.6
3,2026-06-22,53.0,75,89,53,0.37,42.78,-84.6
4,2026-06-23,55.0,77,83,48,NaN,42.78,-84.6
5,2026-06-24,55.0,75,87,55,NaN,42.78,-84.6
6,2026-06-25,NaN,77,90,56,NaN,42.78,-84.6

### Examine temperatures in detail

Temps are not forecasted for today depending on what time it is.  Meteorologists assume the min temp will happen prior to Noon, and if it's already happened, it's not a forecast.   (this is an incorrect assumptions, there are many days when the min temp happens after noon)

In [ ]:
# get a response
units = "US"  # use us units to compare with NWS forecast
resp = ndfd.request_ndfd_digital_forecast(lat=lat, lon=lon, 
                                          user_agents = ndfd.DEFAULT_USER_AGENT, 
                                          units=units)
print(resp.text)

look at XML for temperatures

In [8]:
root = ndfd.ET.fromstring(resp.text)

metric_path = ".//temperature[@type='minimum']"
metric_name = ndfd.weather_metric_name_from_xml(root, metric_path)
min_temperature_df = ndfd.weather_metric_xml_to_df(root, metric_path)
min_temperature_df
    # metric_df_list.append( 
    #     pd.DataFrame(
    #         { 
    #         f'{metric_name}': min_temperature_df.groupby('forecast_date')['value'].min()
    #         }
    #     )
    # )

               forecast_time  value forecast_date
0  2026-06-19T20:00:00-04:00     53    2026-06-19
1  2026-06-20T20:00:00-04:00     53    2026-06-20
2  2026-06-21T20:00:00-04:00     55    2026-06-21
3  2026-06-22T20:00:00-04:00     53    2026-06-22
4  2026-06-23T20:00:00-04:00     55    2026-06-23
5  2026-06-24T20:00:00-04:00     55    2026-06-24